import Head from 'next/head';
import { Container, Title } from '@mantine/core';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>  
        <main>
          <Title>Steam Achievements Theme</Title>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In congue, leo eget lobortis faucibus, urna sem ultricies leo, nec mollis velit purus sed ipsum. Maecenas pulvinar velit eget faucibus accumsan. </p>
          <p>Integer vel aliquam arcu. Donec nisi orci, tristique id dignissim sed, placerat id tortor. Pellentesque pharetra maximus ultricies. Sed et magna euismod, facilisis magna sit amet, interdum lacus.</p>
          <p>Integer vestibulum mauris in felis tincidunt, eu lobortis tellus interdum. Praesent eu justo euismod, imperdiet ligula eu, egestas sapien.</p>
        </main>
      </Container>
    </>
  )
}
