import Head from 'next/head';
import { useForm } from '@mantine/form';
import {
  Container,
  TextInput,
  Paper,
  Button,
  Flex,
  Title,
  Text,
} from '@mantine/core';

export default function Home() {
  const form = useForm({
    initialValues: {
      steamId: '',
    },

    validate: {
      steamId: (value) => (value.length === 17 ? null : 'Please enter a valid Steam ID or custom URL'),
    },
  })
  return (
    <>
      <Head>
        <title>Steam Achievements</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container size={500}>
          <Title align="center" my={20}>Steam Achievements</Title>
          <Paper radius="md" p="xl" withBorder>
            <form
              onSubmit={form.onSubmit((values) => {
                console.log(values);
              })}
            >
              <Text mb={10}>Search for a Steam ID or custom URL</Text>
              <Flex gap={15} justify="center" align="flex-start">
                <TextInput
                  required
                  name="steamId"
                  aria-label="Enter a Steam ID or custom URL"
                  value={form.values.steamId}
                  onChange={(event) => form.setFieldValue('steamId', event.currentTarget.value)}
                  error={form.errors.steamId && 'Please enter a valid Steam ID or custom URL'}
                  style={{ flexGrow: 1}}
                />
                <Button type="submit">Find Profile</Button>
              </Flex>
            </form>
          </Paper>
        </Container>
      </main>
    </>
  )
}
